name: Build .deb

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: Install iOS 16.5 SDK
        run: |
          cd $HOME/theos/sdks
          git clone --depth=1 --filter=blob:none --no-checkout https://github.com/xybp888/iOS-SDKs.git
          cd iOS-SDKs
          git sparse-checkout init --cone
          git sparse-checkout set iPhoneOS16.5.sdk
          git checkout
          mv iPhoneOS16.5.sdk ..
          cd .. && rm -rf iOS-SDKs

      - name: Install ldid
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install ldid

      - name: Build
        run: |
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - uses: actions/upload-artifact@v4
        with:
          name: iOS26Anim-deb
          path: packages/*.deb
          if-no-files-found: ignore
